"""
Django settings for lrms_project project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-local-dev')

# SECURITY WARNING: don't run with debug turned on in production!
# Handle DEBUG properly - check for string "False" or "True"
debug_value = config('DEBUG', default='True')
if isinstance(debug_value, str):
    DEBUG = debug_value.lower() in ('true', '1', 'yes', 'on')
else:
    DEBUG = bool(debug_value)

# Handle ALLOWED_HOSTS properly
allowed_hosts_str = config('ALLOWED_HOSTS', default='')
if allowed_hosts_str:
    ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_str.split(',') if host.strip()]
else:
    ALLOWED_HOSTS = []

# Always add Railway domain (critical for deployment)
railway_domain = 'web-production-6cd81.up.railway.app'
if railway_domain not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(railway_domain)

# Also add wildcard for Railway subdomains (more flexible)
if '*' not in ALLOWED_HOSTS and not DEBUG:
    ALLOWED_HOSTS.append('*')

# CSRF Trusted Origins (required for HTTPS)
CSRF_TRUSTED_ORIGINS = [
    'https://web-production-6cd81.up.railway.app',
    'http://web-production-6cd81.up.railway.app',
]

# Also add from environment variable if provided
csrf_origins_str = config('CSRF_TRUSTED_ORIGINS', default='')
if csrf_origins_str:
    additional_origins = [origin.strip() for origin in csrf_origins_str.split(',') if origin.strip()]
    CSRF_TRUSTED_ORIGINS.extend(additional_origins)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'authentication',
    'tickets',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lrms_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lrms_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Get database configuration from environment
db_engine = config('DB_ENGINE', default='').strip()
db_name = config('DB_NAME', default='').strip()
db_user = config('DB_USER', default='').strip()
db_password = config('DB_PASSWORD', default='').strip()
db_host = config('DB_HOST', default='').strip()
db_port = config('DB_PORT', default='').strip()
db_sslmode = config('DB_SSLMODE', default='require').strip()

# Check if we're in production (Railway) - detect by checking for Railway environment
# or if DB_HOST contains 'supabase' or 'railway'
is_production = (
    'RAILWAY_ENVIRONMENT' in os.environ or 
    'RAILWAY_PROJECT_ID' in os.environ or
    'supabase' in db_host.lower() or
    'railway' in db_host.lower()
)

# Use PostgreSQL if we have the required variables OR if we're in production
if (db_host and db_name and db_user) or (is_production and db_host):
    # Force PostgreSQL for production
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': db_name or 'postgres',
            'USER': db_user or 'postgres',
            'PASSWORD': db_password,
            'HOST': db_host,
            'PORT': db_port or '5432',
            'OPTIONS': {
                'sslmode': db_sslmode or 'require',
            },
            'CONN_MAX_AGE': 600,  # Connection pooling
        }
    }
else:
    # Fall back to SQLite only for local development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Use different storage for testing
import sys
if 'test' in sys.argv:
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
else:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Custom User Model
AUTH_USER_MODEL = 'authentication.User'

# Login/Logout URLs
LOGIN_URL = '/auth/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/auth/login/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
