# Generated by Django 5.0.1 on 2025-11-06 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('hr', 'HR'), ('finance', 'Finance'), ('it', 'IT'), ('marketing', 'Marketing'), ('operations', 'Operations'), ('legal', 'Legal'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
