# Generated by Django 5.0.1 on 2025-10-20 05:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(choices=[('hr', 'HR'), ('finance', 'Finance'), ('it', 'IT'), ('marketing', 'Marketing'), ('operations', 'Operations'), ('legal', 'Legal'), ('other', 'Other')], max_length=20)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('nature_of_engagement', models.CharField(choices=[('for_copy', 'For Copy'), ('for_review', 'For Review'), ('for_access', 'For Access'), ('for_data_breach', 'For Data Breach Notification')], max_length=20)),
                ('document_attached', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('details_of_contracting_party', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_comments', models.TextField(blank=True, null=True)),
                ('reviewed_document', models.FileField(blank=True, null=True, upload_to='reviewed_documents/')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
