# Generated by Django 5.0.1 on 2025-10-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticketmessage_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='company',
            field=models.CharField(blank=True, choices=[('company_a', 'Company A'), ('company_b', 'Company B'), ('company_c', 'Company C'), ('company_d', 'Company D'), ('company_e', 'Company E'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
