# Generated by Django 5.0.1 on 2025-10-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='company',
            field=models.CharField(blank=True, choices=[('company_a', 'Medicare Plus Inc.'), ('company_b', 'Care Center'), ('company_c', 'Vidacure'), ('company_d', 'Company D'), ('company_e', 'Company E'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
